//TODO: ICandidate needs to be deleted from the whole app before production.
import { ICandidate } from '@/modules/Candidates/typings';

const candidates: ICandidate[] = [
  {
    id: 1,
    firstName: 'Dodo',
    lastName: 'A',
    employer: 'Cancun IT',
    created: new Date('01 Feb 1995 00:00:00 CST'),
    jobTitle: 'React',
    positions: [],
    recruiters: [{ name: 'Joselyn', role: 'role' }],
    status: '1',
    stage: 'active',
    email: 'test@ksquareinc.com',
    phone: '9998776655',
    website: 'candidatewebsite.com',
  },
  {
    id: 2,
    firstName: 'Dodo',
    lastName: 'B',
    employer: 'Nearsoft',
    created: new Date('01 Feb 1995 00:00:00 CST'),
    jobTitle: 'React',
    positions: [],
    recruiters: [
      { name: 'Alma', role: 'role' },
      { name: 'Darcy', role: 'role' },
    ],
    status: '1',
    stage: 'active',
    email: 'test@ksquareinc.com',
    phone: '9998776655',
    website: 'candidatewebsite.com',
  },
  {
    id: 3,
    firstName: 'Dodo',
    lastName: 'C',
    employer: 'Cancun IT',
    created: new Date('01 Feb 1995 00:00:00 CST'),
    jobTitle: 'React',
    positions: [],
    recruiters: [{ name: 'Joselyn', role: 'role' }],
    status: '1',
    stage: 'active',
    email: 'test@ksquareinc.com',
    phone: '9998776655',
    website: 'candidatewebsite.com',
  },
  {
    id: 4,
    firstName: 'Dodo',
    lastName: 'D',
    employer: 'Nearsoft',
    created: new Date('01 Feb 1995 00:00:00 CST'),
    jobTitle: 'React',
    positions: [],
    recruiters: [
      { name: 'Joselyn', role: 'role' },
      { name: 'Alma', role: 'role' },
    ],
    status: '1',
    stage: 'active',
    email: 'test@ksquareinc.com',
    phone: '9998776655',
    website: 'candidatewebsite.com',
  },
  {
    id: 5,
    firstName: 'Dodo',
    lastName: 'E',
    employer: 'Nearsoft',
    created: new Date('01 Feb 1995 00:00:00 CST'),
    jobTitle: 'React',
    positions: [],
    recruiters: [{ name: 'Joselyn', role: 'role' }],
    status: '1',
    stage: 'active',
    email: 'test@ksquareinc.com',
    phone: '9998776655',
    website: 'candidatewebsite.com',
  },
  {
    id: 6,
    firstName: 'Dodo',
    lastName: 'F',
    employer: 'Nearsoft',
    created: new Date('01 Feb 1995 00:00:00 CST'),
    jobTitle: 'React',
    positions: [],
    recruiters: [
      { name: 'Joselyn', role: 'role' },
      { name: 'Darcy', role: 'role' },
    ],
    status: '1',
    stage: 'active',
    email: 'test@ksquareinc.com',
    phone: '9998776655',
    website: 'candidatewebsite.com',
  },
  {
    id: 7,
    firstName: 'Dodo',
    lastName: 'G',
    employer: 'Cancun IT',
    created: new Date('01 Feb 1995 00:00:00 CST'),
    jobTitle: 'React',
    positions: [],
    recruiters: [{ name: 'Joselyn', role: 'role' }],
    status: '1',
    stage: 'active',
    email: 'test@ksquareinc.com',
    phone: '9998776655',
    website: 'candidatewebsite.com',
  },
  {
    id: 8,
    firstName: 'Dodo',
    lastName: 'H',
    employer: 'Cancun IT',
    created: new Date('01 Feb 1995 00:00:00 CST'),
    jobTitle: 'React',
    positions: [],
    recruiters: [
      { name: 'Joselyn', role: 'role' },
      { name: 'Darcy', role: 'role' },
    ],
    status: '1',
    stage: 'active',
    email: 'test@ksquareinc.com',
    phone: '9998776655',
    website: 'candidatewebsite.com',
  },
  {
    id: 9,
    firstName: 'Dodo',
    lastName: 'I',
    employer: 'Cancun IT',
    created: new Date('01 Feb 1995 00:00:00 CST'),
    jobTitle: 'React',
    positions: [],
    recruiters: [{ name: 'Darcy', role: 'role' }],
    status: '1',
    stage: 'active',
    email: 'test@ksquareinc.com',
    phone: '9998776655',
    website: 'candidatewebsite.com',
  },
  {
    id: 10,
    firstName: 'Dodo',
    lastName: 'J',
    employer: 'Cancun IT',
    created: new Date('01 Feb 1995 00:00:00 CST'),
    jobTitle: 'React',
    positions: [],
    recruiters: [{ name: 'Darcy', role: 'role' }],
    status: '1',
    stage: 'active',
    email: 'test@ksquareinc.com',
    phone: '9998776655',
    website: 'candidatewebsite.com',
  },
  {
    id: 11,
    firstName: 'Dodo',
    lastName: 'K',
    employer: 'Cancun IT',
    created: new Date('01 Feb 1995 00:00:00 CST'),
    jobTitle: 'React',
    positions: [],
    recruiters: [{ name: 'Darcy', role: 'role' }],
    status: '1',
    stage: 'active',
    email: 'test@ksquareinc.com',
    phone: '9998776655',
    website: 'candidatewebsite.com',
  },
  {
    id: 12,
    firstName: 'Dodo',
    lastName: 'L',
    employer: 'Cancun IT',
    created: new Date('01 Feb 1995 00:00:00 CST'),
    jobTitle: 'React',
    positions: [],
    recruiters: [{ name: 'Alma', role: 'role' }],
    status: '1',
    stage: 'active',
    email: 'test@ksquareinc.com',
    phone: '9998776655',
    website: 'candidatewebsite.com',
  },
];

const getAll = (): Promise<ICandidate[]> => {
  return new Promise(resolve => {
    setTimeout(() => resolve(candidates), 2000);
  });
};

export default {
  getAll,
};
